### ISSUE TITLE
911 Authorization malformed

### ISSUE THREAD

**Issue by welovewebs** [raceybe/cpanel-ddns#2]
Hi,

Thanks for this script.
I'm trying to get this working in OpenWRT (luci-app-ddns(ddns-scripts)), but I get a response of 911 Authorization malformed.
In the LuCI (web interface for OpenWRT) interface, i have put the following in the 'Custom update URL' field
https://[USERNAME]:[PASSWORD]@ddns.example.net/update?hostname=[DOMAIN]&myip=[IP]

I have verified that the script is working on my WHM cPanel account, using the included testclient.php script.
(By the way, why is there a /nic/ used in the URL in that script?)

Do you have any experience with OpenWRT, or can you see from the URL I'm trying above, where it might be failing?
(there is an option in luce-app-ddns to say 'Use HTTP Secure'; this is unchecked at the moment)

Cheers,
Stephen

EDIT: If it helps, var_dump($requestAuthString) is NULL before `if (!substr($requestAuthString, 0, 5) == "Basic ") {`
EDITEDIT: This appears to have been caused by the arrays for user/pass/ddns address not parsing. and I believe I have managed to get past this now.
When I try and build the curl manually in SSH on the cPanel server, it responds with '911 new IP address not specified'

`curl http://username:password@ddns.example.com/nic/update?hostname=myddnsname@example.com&myip=1.2.3.4
root@OpenWRT:~# array(1) {
  ["hostname"]=>
  string(30) "myddnsname.example.com"
}
911 new IP address not specified`

but I still get '911 Authorization malformed' in the logfile viewer in OpenWRT

**Comment by raceybe** [comment]
Ah, poor error message...specific, but doesn't help. From the code:

`
if (!substr($requestAuthString, 0, 5) == "Basic ") {
	exit('911\nAuthorization malformed');
}
`

this means the auth header isn't being passed along...I'm not positive, but I think a browser request will strip the user:password or something like that. In any case, for it to work you need to specify the actual header to include the Basic authorization attribute. Try setting the header explicitly for the curl command with `-H'Authorization: Basic user:password'`

The `nic` part of the url is because that's what a dyndns2 protocol request is sent to, at least from what I learned when initially developing. My ubiquiti ER-X uses ddclient for DDNS, and connects appropriately with everything according to the dyndns2 protocol.

I have not tested anything with doing a direct URL update, so I'm not sure it can be done without the authorization header being explicitly set.

**Comment by raceybe** [comment]
The `nic` part of the url is because that's what a dyndns2 protocol request is sent to, at least from what I learned when initially developing. My ubiquiti ER-X uses ddclient for DDNS, and connects appropriately with everything according to the dyndns2 protocol.

**Comment by welovewebs** [comment]
Hi,

Thanks for replying!
I tried explicitly specifying the header, but I got '911 Authorization password not provided' 👍 

How does ddclient send the updates? OpenWRT has the possibility for a custom update script, so possibly I could translate ddclient's method to a script that would work with OpenWRT?

I am also seeking advice on the OpenWRT forums, so if I find a solution there, I'll add it here?

The testclient.php script is working just fine, so I just need to find a way to get the below syntax to do the same as that script
`http://[USERNAME]:[PASSWORD]@ddns.example.net/nic/update?hostname=[DOMAIN]&myip=[IP]`

**Comment by raceybe** [comment]
that is still an issue with the request header I think...let me try it on my connection...ok, I see the same with this syntax:

`curl -H'Authorization: Basic remote:longpasswordstringhere' 'https://ddns.example.net/nic/update?hostname=remote.example.net&myip=1.2.3.4'`

**Comment by raceybe** [comment]
d'oh! from the test client code, it expects a base64 encoded user:password string for Basic authorization...so you need to do that before sending the manual curl request with the explicitly set header...something like:

`Authorization: Basic dXNlcjpwYXNzd29yZA==`

that is a part of basic http authorization, not part of my code. I was bitten by this when manually setting headers a while back. I still think my comment about a browser request stripping out the user:password combination, or something like that.

**Comment by ddaddy** [comment]
Is OpenWRT similar to DD-WRT?
I use these settings on DD-WRT
![image](https://user-images.githubusercontent.com/1425808/97815349-375cf880-1c85-11eb-8ab4-595791324fce.jpeg)

**Comment by raceybe** [comment]
I suspect ddwrt uses ddclient as well with the dyndns2 protocol with a custom update server...that is an important part since it specifies the url used for the update, and the authentication.

This is where I got my url and other stuff at the start:
https://www.dnsomatic.com/docs/api

the link with /nic/ is now considered the dyndns legacy protocol:
https://help.dyn.com/remote-access-api/perform-update/

you can also see the ddclient source here, and you can search for dyndns2 and their other protocols that could/should easily by this script if desired:
https://sourceforge.net/p/ddclient/code/HEAD/tree/trunk/ddclient

AND last edit...just tested using `curl 'https://user:password@update_url'` and that works too with this script, but it needs to be the url containing the /nic/ path

**Comment by welovewebs** [comment]
`curl -H 'Authorization: Basic openwrt:openwrt' http://ddns.example.com/nic/update?hostname=mydynamichostname
[username@cpanel ddns.example.com]$ curl -H'Authorization: Basic _base64encodedusernamepassword_' http://ddns.example.com/nic/update?hostname=mydynamichostname&myip=mypublicip
[1] 2655967
[username@cpanel ddns.example.com]$ array(1) {
  ["hostname"]=>
  string(30) "mydynamichostname"
}
911 new IP address not specified`

> 
> 
> d'oh! from the test client code, it expects a base64 encoded user:password string for Basic authorization...so you need to do that before sending the manual curl request with the explicitly set header...something like:
> 
> `Authorization: Basic dXNlcjpwYXNzd29yZA==`
> 
> that is a part of basic http authorization, not part of my code. I was bitten by this when manually setting headers a while back. I still think my comment about a browser request stripping out the user:password combination, or something like that.

Yeah, that works. So I just need to figure out how to either, preferably, get OpenWRT to base64encode [USERNAME]:{PASSWORD] or remove that requirement from your script

**Comment by welovewebs** [comment]
> 
> 
> Is OpenWRT similar to DD-WRT?
> I use these settings on DD-WRT
> ![image](https://user-images.githubusercontent.com/1425808/97815349-375cf880-1c85-11eb-8ab4-595791324fce.jpeg)

So DD-WRT must be bsae64encoding the credentials then?

**Comment by raceybe** [comment]
The base64 encoding is part of http basic authentication: https://en.wikipedia.org/wiki/Basic_access_authentication not a part of the script. If you are specifying the header directly, you need to base64 encode the user:password string. If providing in the url, then you just do user:password@url

You can specify the creds in the clear if included in the update url and I've done it fine on my end. Is this an OpenWRT template string of some sort? If so, make sure the nic portion is there.

`https://[USERNAME]:[PASSWORD]@ddns.example.net/nic/update?hostname=[DOMAIN]&myip=[IP]`

What happens when using curl if you put the full url in single quotes? You can also check the server apache access log to see what GET is issued, since the hostname and myip fields should be present there.  That is exactly the syntax I'm using with my manual test, only difference being that I added the single quotes.

Update: I just tested curl without quotes, and it gives the error you're seeing.

**Comment by welovewebs** [comment]
Hi,

If I put quotes round the full string in the OpenWRT interface, it doesn't like it.
Curl from SSH on OpenWRT or on the WHM/cPanel server works just fine

My cPanel server is running LiteSpeed and I can't find the logs where one might expect :/

**Comment by raceybe** [comment]
I just checked my logs and indeed it looks like `myip` is omitted for my requests without quotes. I'd be curious in your scenario to see what happens if you reverse the appearance of the `hostname` and `myip` arguments in the url.

After scanning the OpenWRT DDNS Client page
https://openwrt.org/docs/guide-user/services/ddns/client
it looks like they may not be using ddclient afterall. They also mention the default might be using wget but you can configure it to use curl. Beyond that, I probably won't be much help with OpenWRT.

**Comment by welovewebs** [comment]
I swapped the `hostname` and `myip` around in that URL, but it still can't get past the authorization malformed because (I suspect) OpenWRT is not base64encoding the credentials.

As I said, using curl from SSH on either end works just fine.

![tempsnip](https://user-images.githubusercontent.com/11460430/97816645-80657a80-1c8e-11eb-8850-386b114c93da.png)
I'm wondering what goes in 'Custom update-script'

**Comment by welovewebs** [comment]
> They also mention the default might be using wget but you can configure it to use curl. Beyond that, I probably won't be much help with OpenWRT.
Yep, I'm not sure how I force ddns-script to use curl instead of wget to try

[https://openwrt.org/docs/guide-user/services/ddns/client](url)
According to the documentation here, it says I can configure whether to prefer wget or curl and that it defaults to wget, but I cna't see where to configure it to use curl

**Comment by raceybe** [comment]
I think the base64 encoding should be automatic if using the user:password format in front of the server name in the url. You can try returning the entire `$requestAuthString` to see what the header content is.

There is one more thing you can try in your copy of the script. Add this to the beginning of the .htaccess file:
```
CGIPassAuth on
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```
and replace
```
$requestAuthString
```
in the base64_decode call with this
```
$_SERVER['REDIRECT_HTTP_AUTHORIZATION']
```

I don't know if both methods dump the same request headers or not, but maybe either your Apache or OpenWRT is doing something else with them...

**Comment by welovewebs** [comment]
Hi,

Thanks for sticking with me and all your efforts!!
I finally managed to find how to configure _ddns-scripts_ to use curl and now _luci-app-ddns_ is updating your script quite happily.
Although the documentation on openwrt.org made mention of the ability to do so, nowhere did it say how!
EDIT: _a correction to the above, it does say how, but to my mind it's unclear and I had to find out from elsewhere_

Anyway, if anyone else trawling the net finds this, the solution is to add `option use_curl '1'` to the `config ddns 'global'` section of _/etc/config/ddns_ on OpenWRT; I don't think this can be specified in LuCI.

So, **raceybe**, great job and you now know it works with OpenWRT too :D

Thanks again for the script and your help

**Comment by raceybe** [comment]
haha, you're welcome. I picked it up again since I might be moving to an ISP without static IP options. I'll close the issue?

**Comment by welovewebs** [comment]
Yeah, sure. (will it remain visible to anyone searching for a solution? I'm new to discussions on GitHub)

**Comment by raceybe** [comment]
Yes, I'm still pretty new to actually using GitHub, but this discussion will remain.
